name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        
        days-before-stale: 90
        days-before-close: 14
        exempt-all-milestones: true
        operations-per-run: 5

        stale-issue-label: 'no-issue-activity'
        exempt-issue-labels: 'pinned,security'
        stale-issue-message: |
          This issue has been automatically marked as stale because it has not had
          recent activity. It will be closed if no further activity occurs.
          Thank you for your contributions.
        close-issue-reason: 'not_planned'
        
        stale-pr-label: 'no-pr-activity'
        exempt-pr-labels: 'pinned,security'
        stale-pr-message: |
          This pull request has been automatically marked as stale because it has not had
          recent activity. It will be closed if no further activity occurs.
          Thank you for your contributions.
